import { HomeContent, MenuItem } from '../types';

export const mockHomeContent: HomeContent[] = [
  {
    id: '1',
    section: 'hero',
    title: 'Chào mừng đến với Trung tâm Anh ngữ',
    subtitle: 'Nơi khơi dậy tiềm năng ngôn ngữ của bạn',
    description: 'Trung tâm Anh ngữ chúng tôi cam kết mang đến chất lượng giáo dục tốt nhất với đội ngũ giảng viên giàu kinh nghiệm.',
    content: '<p>Chúng tôi cung cấp các khóa học tiếng Anh chất lượng cao cho mọi lứa tuổi, từ trẻ em đến người lớn.</p>',
    imageUrl: '/images/hero-banner.jpg',
    buttonText: 'Bắt đầu ngay',
    buttonLink: '/courses',
    order: 1,
    isActive: true,
    createdAt: '2024-01-01T00:00:00.000Z',
    updatedAt: '2024-01-01T00:00:00.000Z'
  },
  {
    id: '2',
    section: 'about',
    title: 'Về chúng tôi',
    subtitle: 'Hơn 10 năm kinh nghiệm trong lĩnh vực giáo dục',
    description: 'Trung tâm Anh ngữ được thành lập năm 2010 với sứ mệnh mang đến chất lượng đào tạo tiếng Anh tốt nhất.',
    content: '<p>Với đội ngũ giảng viên giàu kinh nghiệm và phương pháp giảng dạy hiện đại, chúng tôi đã đào tạo hơn 10,000 học viên.</p>',
    imageUrl: '',
    buttonText: 'Tìm hiểu thêm',
    buttonLink: '/about',
    order: 1,
    isActive: true,
    createdAt: '2024-01-01T00:00:00.000Z',
    updatedAt: '2024-01-01T00:00:00.000Z'
  },
  {
    id: '3',
    section: 'services',
    title: 'Tiếng Anh Giao tiếp',
    subtitle: 'Khóa học thực tế, hiệu quả',
    description: 'Khóa học tiếng Anh giao tiếp được thiết kế đặc biệt cho người Việt Nam.',
    content: '<p>Học viên sẽ được thực hành giao tiếp với giáo viên bản ngữ và các tình huống thực tế.</p>',
    imageUrl: '/images/conversation.jpg',
    buttonText: 'Đăng ký ngay',
    buttonLink: '/courses/conversation',
    order: 1,
    isActive: true,
    createdAt: '2024-01-01T00:00:00.000Z',
    updatedAt: '2024-01-01T00:00:00.000Z'
  },
  {
    id: '4',
    section: 'services',
    title: 'Luyện thi IELTS',
    subtitle: 'Chuẩn bị tốt nhất cho kỳ thi',
    description: 'Khóa học luyện thi IELTS với phương pháp hiện đại và đội ngũ giảng viên chuyên môn cao.',
    content: '<p>Cam kết điểm số IELTS từ 6.0 trở lên sau khóa học.</p>',
    imageUrl: '/images/ielts.jpg',
    buttonText: 'Tư vấn miễn phí',
    buttonLink: '/courses/ielts',
    order: 2,
    isActive: true,
    createdAt: '2024-01-01T00:00:00.000Z',
    updatedAt: '2024-01-01T00:00:00.000Z'
  },
  {
    id: '5',
    section: 'services',
    title: 'Tiếng Anh Trẻ em',
    subtitle: 'Phương pháp học phù hợp với trẻ em',
    description: 'Khóa học tiếng Anh dành riêng cho trẻ em từ 4-12 tuổi.',
    content: '<p>Sử dụng phương pháp học thông qua trò chơi và hoạt động tương tác.</p>',
    imageUrl: '/images/kids.jpg',
    buttonText: 'Đăng ký học thử',
    buttonLink: '/courses/kids',
    order: 3,
    isActive: true,
    createdAt: '2024-01-01T00:00:00.000Z',
    updatedAt: '2024-01-01T00:00:00.000Z'
  },
  {
    id: '6',
    section: 'features',
    title: 'Giảng viên chất lượng',
    subtitle: 'Đội ngũ giảng viên giàu kinh nghiệm',
    description: '100% giảng viên có bằng cấp quốc tế và kinh nghiệm giảng dạy.',
    content: '<p>Giảng viên được tuyển chọn kỹ lưỡng và đào tạo thường xuyên.</p>',
    imageUrl: '/images/teacher.jpg',
    buttonText: '',
    buttonLink: '',
    order: 1,
    isActive: true,
    createdAt: '2024-01-01T00:00:00.000Z',
    updatedAt: '2024-01-01T00:00:00.000Z'
  },
  {
    id: '7',
    section: 'features',
    title: 'Phương pháp hiện đại',
    subtitle: 'Áp dụng công nghệ giảng dạy tiên tiến',
    description: 'Sử dụng công nghệ AI và phương pháp học tập hiện đại.',
    content: '<p>Kết hợp học trực tuyến và offline để tối ưu hiệu quả học tập.</p>',
    imageUrl: '/images/technology.jpg',
    buttonText: '',
    buttonLink: '',
    order: 2,
    isActive: true,
    createdAt: '2024-01-01T00:00:00.000Z',
    updatedAt: '2024-01-01T00:00:00.000Z'
  },
  {
    id: '8',
    section: 'features',
    title: 'Môi trường học tập',
    subtitle: 'Cơ sở vật chất hiện đại, thoải mái',
    description: 'Phòng học được trang bị đầy đủ thiết bị hiện đại.',
    content: '<p>Môi trường học tập thân thiện, khuyến khích sự sáng tạo.</p>',
    imageUrl: '/images/classroom.jpg',
    buttonText: '',
    buttonLink: '',
    order: 3,
    isActive: true,
    createdAt: '2024-01-01T00:00:00.000Z',
    updatedAt: '2024-01-01T00:00:00.000Z'
  },
  {
    id: '9',
    section: 'testimonials',
    title: 'Nguyễn Văn A',
    subtitle: 'Học viên khóa IELTS',
    description: 'Khóa học rất bổ ích, giảng viên nhiệt tình và phương pháp giảng dạy hiệu quả.',
    content: 'Tôi đã đạt được điểm IELTS 7.0 sau 3 tháng học tại trung tâm.',
    imageUrl: '/images/student1.jpg',
    buttonText: '',
    buttonLink: '',
    order: 1,
    isActive: true,
    createdAt: '2024-01-01T00:00:00.000Z',
    updatedAt: '2024-01-01T00:00:00.000Z'
  },
  {
    id: '10',
    section: 'testimonials',
    title: 'Trần Thị B',
    subtitle: 'Phụ huynh học sinh',
    description: 'Con tôi rất thích học tại trung tâm, phương pháp giảng dạy phù hợp với trẻ em.',
    content: 'Sau 6 tháng học, con tôi đã tự tin giao tiếp bằng tiếng Anh.',
    imageUrl: '/images/parent1.jpg',
    buttonText: '',
    buttonLink: '',
    order: 2,
    isActive: true,
    createdAt: '2024-01-01T00:00:00.000Z',
    updatedAt: '2024-01-01T00:00:00.000Z'
  },
  {
    id: '11',
    section: 'contact',
    title: 'Liên hệ với chúng tôi',
    subtitle: 'Hãy để chúng tôi tư vấn cho bạn',
    description: 'Đội ngũ tư vấn viên chuyên nghiệp sẽ giúp bạn chọn khóa học phù hợp.',
    content: '<p>Hotline: 1900-xxxx<br>Email: info@englishcenter.com<br>Địa chỉ: 123 Đường ABC, Quận XYZ, TP.HCM</p>',
    imageUrl: '',
    buttonText: 'Liên hệ ngay',
    buttonLink: '/contact',
    order: 1,
    isActive: true,
    createdAt: '2024-01-01T00:00:00.000Z',
    updatedAt: '2024-01-01T00:00:00.000Z'
  },
  {
    id: '12',
    section: 'footer',
    title: '© 2024 Trung tâm Anh ngữ',
    subtitle: '',
    description: 'Tất cả quyền được bảo lưu.',
    content: '<p>Trung tâm Anh ngữ - Nơi khơi dậy tiềm năng ngôn ngữ của bạn</p>',
    imageUrl: '',
    buttonText: '',
    buttonLink: '',
    order: 1,
    isActive: true,
    createdAt: '2024-01-01T00:00:00.000Z',
    updatedAt: '2024-01-01T00:00:00.000Z'
  }
];

export const mockMenuItems: MenuItem[] = [
  {
    id: '1',
    label: 'Trang chủ',
    sectionId: 'hero-section',
    order: 1,
    isActive: true,
    isExternal: false,
    externalUrl: ''
  },
  {
    id: '2',
    label: 'Về chúng tôi',
    sectionId: 'about-section',
    order: 2,
    isActive: true,
    isExternal: false,
    externalUrl: ''
  },
  {
    id: '3',
    label: 'Dịch vụ',
    sectionId: 'services-section',
    order: 3,
    isActive: true,
    isExternal: false,
    externalUrl: ''
  },
  {
    id: '4',
    label: 'Tính năng',
    sectionId: 'features-section',
    order: 4,
    isActive: true,
    isExternal: false,
    externalUrl: ''
  },
  {
    id: '5',
    label: 'Đánh giá',
    sectionId: 'testimonials-section',
    order: 5,
    isActive: true,
    isExternal: false,
    externalUrl: ''
  },
  {
    id: '6',
    label: 'Liên hệ',
    sectionId: 'contact-section',
    order: 6,
    isActive: true,
    isExternal: false,
    externalUrl: ''
  }
];
